version: 2.1

# ############################################
#
# Set Circle CI Reusable Commands
#
# For more information, see the documentation:
# https://circleci.com/docs/2.0/reusing-config
#
# ############################################
commands:
  clean-up-channels:
    description: "Reusable non-model unit test commands"
    parameters:
      n_retain:
        type: integer
      channels:
        type: string
      keyname:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup
          command: |
            pip install -r requirements.txt
      - run:
          name: Reap messages
          command: |
            python reaper.py \
              --n-retain << parameters.n_retain >> \
              --wait-for 600 \
              --channels << parameters.channels >> \
              --keyname << parameters.keyname >>

jobs:
  # personal workspace
  personal-slack-reaper:
    working_directory: ~/slack-reaper
    docker:
      - image: python:3.7
    steps:
      - clean-up-channels:
          n_retain: 5000
          channels: general
          keyname: PERSONAL_REAPER_SLACK_APP_TOKEN

  # TODO: open source workspace

workflows:
  version: 2
  reaper:
    triggers:
      - schedule:
          # 17:00 on Tuesdays (~noon CST)
          cron: "0 17 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
        - personal-slack-reaper
