version: 2.1

# ################################
#
# CircleCI Job Filters
#
# ################################
test-filters: &test-filters
    tags:
        only: /.*/
    branches:
        only: /.*/

deploy-filters: &deploy-filters
    tags:
        only: /.*/
    branches:
        ignore: /.*/


jobs:
    slack-reaper:
      working_directory: ~/slack-reaper
      docker:
        - image: python:3.7
      steps:
        - checkout
        - run:
            name: Setup
            command: |
              pip install -r requirements.txt
        - run:
            name: Reap messages
            command: |
              python reaper.py --n-retain 5000 --wait-for 600 --channels general

workflows:
  version: 2
  reaper:
    triggers:
      - schedule:
          # 17:00 on Tuesdays (~noon CST)
          cron: "0 17 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
        - slack-reaper
