version: 2.1

# ############################################
#
# Set Circle CI Reusable Commands
#
# For more information, see the documentation:
# https://circleci.com/docs/2.0/reusing-config
#
# ############################################
commands:
  clean-up-channels:
    description: "Reusable non-model unit test commands"
    parameters:
      n_retain:
        type: integer
      channels:
        type: string
      delete_media:
        type: integer
      keyname:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup
          command: |
            pip install -r requirements.txt
      - run:
          name: Reap messages
          command: |
            python reaper.py \
              --n-retain << parameters.n_retain >> \
              --wait-for 600 \
              --channels << parameters.channels >> \
              --delete-media << parameters.delete_media >> \
              --keyname << parameters.keyname >>

jobs:
  # personal workspace
  personal-slack-reaper:
    working_directory: ~/slack-reaper
    docker:
      - image: python:3.7
    steps:
      - clean-up-channels:
          n_retain: 3000
          channels: PERSONAL_REAPER_CHANNELS
          delete_media: 0
          keyname: PERSONAL_REAPER_SLACK_APP_TOKEN

  # open source workspace
  alkaline-slack-reaper:
    working_directory: ~/slack-reaper
    docker:
      - image: python:3.7
    steps:
      - clean-up-channels:
          n_retain: 1000
          channels: ALKALINE_REAPER_CHANNELS
          delete_media: 1
          keyname: ALKALINE_REAPER_SLACK_APP_TOKEN

workflows:
  version: 2

  # Reaper for personal workspace
  personal-reaper:
    triggers:
      - schedule:
          # 17:00 on Tuesdays (11 or 12 CST, depending on DST)
          cron: "0 17 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
        - personal-slack-reaper

  # Reaper for alkaline-ml workspace
  alkaline-reaper:
    triggers:
      - schedule:
          # 15:00 on Mon, Weds & Fri (9 or 11 CST, depending on DST)
          cron: "0 15 * * 1,3,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - alkaline-slack-reaper
